stages:
- build
- release

variables:
  PACKAGE_VERSION: "${CI_COMMIT_TAG}"
  ARCHIVE_NAME: oc.3.x.x.cleverpoint.${CI_COMMIT_TAG}.ocmod.zip
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/opencart/${PACKAGE_VERSION}"

build archive:
  stage: build
  image: alpine:latest
  only:
  - tags
  before_script:
  - apk add --no-cache zip curl
  script:
  - cd oc.3.x.x.cleverpoint.ocmod
  - zip -r ../oc.3.x.x.cleverpoint.ocmod.zip *
  - cd ../
  - |
    curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file oc.3.x.x.cleverpoint.ocmod.zip "${PACKAGE_REGISTRY_URL}/${ARCHIVE_NAME}"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
  - tags
  script:
  - |
    release-cli create --tag-name ${CI_COMMIT_TAG} --name "Release ${CI_COMMIT_TAG}" --assets-link "{\"name\":\"ocmod\",\"url\":\"${PACKAGE_REGISTRY_URL}/${ARCHIVE_NAME}\"}"

